### ISSUE TITLE
[Feature Request] Add Support for Flushing Queue

### ISSUE THREAD

**Issue by amxmln** [tameemsafi/typewriterjs#37]
Hi, thanks for this plugin!

I’m currently using it in a project of mine where the strings to be typed can change before the animation has finished. The way this plugin works now, it finishes the original string, then executes the scheduled "deleteAll" and then types the new string. It would be great if you could add a method to "flush" all changes out of the queue, allowing the "deleteAll" to be handled as soon as it is requested and not after the animation has run.

I hope it’s clear what I mean. Cheers and thanks again!

**Comment by tameemsafi** [comment]
You are able to chain the `deleteAll` function anywhere and it will be called once it reaches that stage.

Example:
https://jsfiddle.net/2dwL47bu/

**Comment by amxmln** [comment]
Thanks for your reply, I am aware of that, the point is that it has to reach that point, i.e. the string has to be fully typed out and there's no way to cancel that and directly skip to the next step.

I was asking for a feature to clear the current event queue and start a new one, so I don’t think this issue is resolved.

**Comment by tameemsafi** [comment]
Thank you for your reply. You are correct regarding the queue system. However, there must be a point in the queue for it to call some kind of method to flush the queue. So it would not be possible to include the function you are requesting. This would essentially mean doing a check after processing each item in the queue in order to flush the queue at the correct point, which I think is incorrect for what you need.

You can achieve what you need through the current API. You can use the javascript `MutationObserver` in order to listen for any changes in the wrapper element. Then you can check if the wrapper element meets a condition and stop the typewriter instance and re-create it again.

Example:
https://jsfiddle.net/yxLmvq8c/

**Comment by amxmln** [comment]
I only glanced over the source code, so I could be wrong here, but wouldn’t a method on the typewriter instance itself suffice? Say there’s a method `flush()` that stops the typewriter and flushes the queue when called externally (so not as part of a chain) and then the queue can be filled again like usual? The state the instance was in could be kept as the initial state for the new queue, i.e. if a word was currently being typed it would still stay visible up to the point it was typed and could be modified by subsequent calls.

In any case, thank you for your example, I guess I could simply replace the typewriter instance whenever I need it to restart—I’ll have to find a way to make it look less jagged though.

**Comment by tameemsafi** [comment]
No problem, I think re-creating the whole instance would be better than flushing the queue as this would only be required in very specific circumstances. You have full control over the object that is created, so you can choose when to re-create it. I hope that works for you, but would be happy to re-consider if it becomes a problem for other users of the plugin.

**Comment by amxmln** [comment]
Yes, I think you have a valid point there. Thanks for your help and suggestions and being open about reconsidering should it come up again! :+1:
