### ISSUE TITLE
[Issue] Emoji are rendered like an unknown char symbol for a second

### ISSUE THREAD

**Issue by roma-glushko** [tameemsafi/typewriterjs#47]
**Description**
I have tried to add emoji to labels that I want to type via Typewriterjs and they are rendered in a weird way. Here is my component init:

```jsx
const titles = [
    'Test 🛠', 
    'Test 2 🛒🐹🧔', 
]
```

```jsx
<Typewriter options={{
   strings: titles,
   autoStart: true,
   loop: true,
}}>
```

**Expected Result**
Emoji is rendered right away without showing unknown char symbol like letters.

**Actual Result**
Emoji is rendered in a way when the unknown char symbol is shown firstly and then the actual emoji is rendered. This is a frustrating experience:

![2019-09-17_09-46-03 (1)](https://user-images.githubusercontent.com/9402690/65017890-7b315900-d930-11e9-9b02-c87b3301cfd4.gif)

Is it possible to fix somehow?

**Comment by tameemsafi** [comment]
@roma-glushko Emoji's work differently to strings so it won't be possible to support them in the typewriter js plugin. This is because it would dramatically increase the file size of the bundle.

However, I have now added an option `stringSplitter` to allow you to define your own custom string splitter which can support emojis. I would recommend using `grapheme-splitter` npm package.

Example:

```js
import GraphemeSplitter from 'grapheme-splitter';
import Typewriter from 'typewriter-effect';

const splitter = new GraphemeSplitter();

const titles = [
    'Test 🛠', 
    'Test 2 🛒🐹🧔', 
]

<Typewriter options={{
   strings: titles,
   autoStart: true,
   loop: true,
  stringSplitter: splitter. splitGraphemes,
}}>
```

**Comment by tameemsafi** [comment]
Live example: https://codesandbox.io/s/typewriter-effect-emojis-pgz6e
